name: Stock Alerts Bot

on:
  schedule:
    - cron: "0 * * * *"   # kör varje hel timme
  workflow_dispatch:      # gör att du kan köra manuellt

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.12"

    - name: Install dependencies
      run: |
        pip install requests gitpython

    - name: Run script
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        NEWSAPI_KEY: ${{ secrets.NEWSAPI_KEY }}
      run: python stock_agent.py

    - name: Push updated alerts.json
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        git add alerts.json
        git commit -m "Update alerts [skip ci]" || echo "No changes to commit"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
